server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  server:
   enable-self-preservation: false  # Tắt chế độ tự bảo vệ trong môi trường phát triển
  client:
   register-with-eureka: false
   fetch-registry: false
